### PR TITLE
home page

### PR DESCRIPTION
**Pull request by andredevjs**
Fixes: https://github.com/Tribe-BTC/tribe-master/issues/42

### CODE REVIEW

**Comment by andredevjs** [comment]
Screenshot 2023-11-04 at 9 19 02 AM

**Comment by andredevjs** [comment]
@dillonhealybtc ready to go, waiting on your feedback/approval

**Comment by dillonhealybtc** [comment]
Approved good to go

**Review by Rsync25 — DISMISSED** [review]

**Comment by Rsync25** [comment]
I approved PR. @andredevjs you can merge it!

**Review by Rsync25 — APPROVED** [review]

**Pull request merged**
